### ISSUE TITLE
grunt-contrib-hardlink: contributing new plugin to grunt-contrib

### ISSUE THREAD

**Issue by oitofelix** [gruntjs/grunt-contrib-symlink#16]
I just published [grunt-contrib-hardlink](https://github.com/oitofelix/grunt-contrib-hardlink) (initially forked from [grunt-contrib-symlink](https://github.com/gruntjs/grunt-contrib-symlink)) which solves the problem of a recursive hard-linking grunt task.  As demonstrated by the issues and pull requests below it's a feature people would find useful.

* https://github.com/gruntjs/grunt-contrib-copy/pull/75
* https://github.com/gruntjs/grunt-contrib-copy/issues/146
* https://github.com/gruntjs/grunt-contrib-copy/pull/147
* https://github.com/gruntjs/grunt/issues/797

I've opened this issue here because I couldn't open one at [grunt-contrib](https://github.com/gruntjs/grunt-contrib), despite the instructions asking for that at [the grunt web page contributing section](http://gruntjs.com/contributing).

**Comment by sindresorhus** [comment]
We're not accepting new plugins. Please also do not use the `grunt-contrib` prefix as it's reserved for contrib plugins.

**Comment by oitofelix** [comment]
That's unfortunate.  May I know why not?

**Comment by vladikoff** [comment]
@oitofelix We are not creating / accepting new `grunt-contrib-*` plugins because we do not have developer hours to support more `contrib` plugins. Please rename your plugin to `grunt-hardlink` to make sure it shows up properly on the plugins page. Thanks!
