### ISSUE TITLE
Can you update the README for idiots like me?

### ISSUE THREAD

**Issue by lolobosse** [gruntjs/grunt-contrib-symlink#20]
Hi there,

I thought that `explicit` was a keyword and I didn't know hot to create a second symlink. Maybe it will be nice to replace this `explicit` by `theNameYouWant` or something like this (for people who are new to grunt structure).

Best,

Thanks for the lib btw!

**Comment by shama** [comment]
Feel free to edit the docs and submit a PR here: https://github.com/gruntjs/grunt-contrib-symlink/blob/master/docs/symlink-examples.md Thanks!
